### PR TITLE
add application_details option for iOS

### PR DESCRIPTION
**Pull request by NickAdriaenssens**

### CODE REVIEW

**Comment by guyromb** [comment]
Hi @NickAdriaenssens , Can you please provide more details / a source?

**Comment by guyromb** [comment]
Thanks @NickAdriaenssens

**Comment by NickAdriaenssens** [comment]
@guyromb Thanks for the quick response!

**Comment by jedofus** [comment]
Hello , redirection of Bluetooth native settings doesn't work on ios , it open general settings .
How can i resolved it ?

**Comment by guyromb** [comment]
which settings constant did you use, which ios version?
I will inspect

**Comment by jedofus** [comment]
`
if (window.cordova && window.cordova.plugins.settings) {
    console.log('openNativeSettingsTest is active');
    window.cordova.plugins.settings.open("bluetooth", function() {
            console.log('opened settings');
        },
        function () {
            console.log('failed to open settings');
        }
    );
} else {
    console.log('openNativeSettingsTest is not active!');
}
`

it work well on android . My ios version : 9.3.3

**Comment by jedofus** [comment]
have you got news of my bluetooth problem?

**Comment by guyromb** [comment]
thanks for your suggestion. Can you please create a pull request for that?

**Pull request merged**
