### PR TITLE
Added iOS 10 support

### PR DESCRIPTION
**Pull request by yazantahhan**

### CODE REVIEW

**Comment by guyromb** [comment]
Can you describe briefly what are the changes?

**Comment by yazantahhan** [comment]
As Apple removed the support of redirecting user programmatically to settings page using "prefs" prefix in iOS 10, it is now supported using "App-Prefs".

What I did:
1) Added macro in header file that checks the iOS version - Credits to [yasirmturk](http://stackoverflow.com/questions/3339722/how-to-check-ios-version/5337804#5337804)
2) Added a variable  "prefix" which by default has the value of "App-Prefs" which is supported in iOS 10. After that, it checks the version of iOS if it is less than 10 then the prefix is "prefs". Then added the prefix and concatenated with the remaining strings.

**Comment by yazantahhan** [comment]
@guyromb I have tested it to open the WiFi settings on iOS 10 on a real device and on iOS 8 on simulator. However, the simulator doesn't have a WiFi settings so it redirected me to the general settings page. Could you please test it on real device if you have one just to make sure that everything is working? 
Thanks

**Comment by guyromb** [comment]
Yes. Thanks!

**Comment by emcniece** [comment]
@yazantahhan just confirming that iOS 10 operation is working fine, and we passed the Apple Review process this week!

**Pull request merged**
